-- Exit levels (Stop Loss / Take Profit) on assets for simulated auto-execution
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "stopLoss" DECIMAL(28,12);
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "tp1" DECIMAL(28,12);
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "tp2" DECIMAL(28,12);
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "tp3" DECIMAL(28,12);
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "tp4" DECIMAL(28,12);
